import './globals.css' 
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import Footer from './Footer'
import { Toaster } from 'react-hot-toast'


export const metadata = {
  title: 'Code Hunter App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" min-h-[100vh] flex flex-col justify-between " >
       
        <Navbar></Navbar>
        <Toaster position='top-right' toastOptions={{
          success:{
            iconTheme:{
              primary:"#0053a6"
            }
          },
          error:{
            iconTheme:{
              primary:"#0053a6"
            }
          }
        }}
        />
        {children}
        <Footer></Footer>
        
        </body>
    </html>
  )
}
